// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_FHE2qcUWl6-hgOlUvRk60zeDqZufVcE',
    appId: '1:822199588970:web:e3f84eaee4aae3b8d91213',
    messagingSenderId: '822199588970',
    projectId: 'martsimple-app',
    authDomain: 'martsimple-app.firebaseapp.com',
    storageBucket: 'martsimple-app.appspot.com',
    measurementId: 'G-RJWM81Q4MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAif6tgsFrRZrRZ1_d8wYDgA0fahlSwnaI',
    appId: '1:822199588970:android:aaf59c3d4e68cff9d91213',
    messagingSenderId: '822199588970',
    projectId: 'martsimple-app',
    storageBucket: 'martsimple-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtae0zPnE1LlX-4AICAkgjFixZ6xDJv4c',
    appId: '1:822199588970:ios:c5020d49fa4a79e2d91213',
    messagingSenderId: '822199588970',
    projectId: 'martsimple-app',
    storageBucket: 'martsimple-app.appspot.com',
    iosClientId: '822199588970-7ol5ehl90r1alvq0pblleopln3cajajr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtae0zPnE1LlX-4AICAkgjFixZ6xDJv4c',
    appId: '1:822199588970:ios:36d43b1565223a15d91213',
    messagingSenderId: '822199588970',
    projectId: 'martsimple-app',
    storageBucket: 'martsimple-app.appspot.com',
    iosClientId: '822199588970-dv1ac6ll8le2if76js00989c93f4f8fv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionApp.RunnerTests',
  );
}
